project/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('email-contact/', views.email_contact, name='api_email_contact'),
]

project/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogPageList.as_view(), name='list'),
    path('<slug:slug>', views.BlogPageDetail.as_view(), name='detail'),

]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    # path('account/', include('account.urls')),
    path('account/', include('allauth.urls')),

    path('', include('core.urls', namespace='core')),
    path('blog/', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

project/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path("", views.HomePage.as_view(), name="home"),
    path("about", views.AboutPage.as_view(), name="about"),
    path("contact-me", views.ContactFormPartialView.as_view(), name="contact_me"),

]

project/core/models.py
import markdown
from django.db import models
from blog.models import Topic
from django.core.exceptions import ValidationError
from django.utils.safestring import mark_safe
from .validators import for_published_status_require_image_not_none

class TestimonialManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status="P")

class Testimonial(models.Model):
    class Status(models.TextChoices):
        EDITING = ("E", "Editing")
        PUBLISHED = ("P", "Published")

    name = models.CharField(max_length=40)
    profession = models.CharField(max_length=80)
    message = models.CharField(max_length=250)
    image = models.FileField(upload_to="testimonials", blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=Status.choices, default=Status.EDITING)

    objects = models.Manager()  
    published = TestimonialManager()

    def clean(self):
        for_published_status_require_image_not_none(self.status, self.image)

    def save(self, *args, **kwargs):
        self.full_clean()
        return super().save(*args, **kwargs)
    
    def publish(self) -> None:
        self.status = Project.Status.PUBLISHED
        self.save()
    
    def unpublish(self) -> None:
        self.status = Project.Status.EDITING
        self.save()

    def __str__(self) -> str:
        return self.name

    class Meta:
        indexes = [
            models.Index(fields=["-created"])
        ]
        ordering = ["-created"]

class ProjectManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status="P")
    
class Project(models.Model):
    class Status(models.TextChoices):
        EDITING = ("E", "Editing")
        PUBLISHED = ("P", "Published")

    customer = models.CharField(max_length=40)
    customer_commercial_field = models.CharField(max_length=80)
    description = models.TextField()
    image = models.FileField(upload_to="projects", blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    tecnologies = models.ManyToManyField(Topic, related_name="projects")
    status = models.CharField(max_length=1, choices=Status.choices, default=Status.EDITING)
    
    objects = models.Manager()  
    published = ProjectManager()
        
    def clean(self):
        for_published_status_require_image_not_none(self.status, self.image)

    def save(self, *args, **kwargs):
        self.full_clean()
        return super().save(*args, **kwargs)
    
    @property
    def description_html(self) -> str:
        return mark_safe(markdown.markdown(self.description))
    
    def publish(self) -> None:
        self.status = Project.Status.PUBLISHED
        self.save()
    
    def unpublish(self) -> None:
        self.status = Project.Status.EDITING
        self.save()

    def __str__(self) -> str:
        return self.name

    class Meta:
        indexes = [
            models.Index(fields=["-created"])
        ]
        ordering = ["-created"]

project/core/forms.py
from typing import Any
from django import forms
from django.core.exceptions import ValidationError
from .task import send_feedback_email_task

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    best_email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)
    
    # trap fields
    username = forms.CharField(required=False)
    email = forms.CharField(required=False)
    
    def clean(self) -> dict[str, Any]:
        """
        checking fields for catch some bots
        """
        cleaned_data = super().clean()
        trap1 = cleaned_data.get("email")
        trap2 = cleaned_data.get("username")

        if trap1 or trap2:
            self.add_error("username", "stop the bot")
        return cleaned_data
    
    def send_email(self) -> None:
        """
        using celery task for send emails
        """
        email = self.cleaned_data.get("best_email")
        name = self.cleaned_data.get("name")
        message = self.cleaned_data.get("message")
        send_feedback_email_task.delay(email, message)

project/core/views.py
from typing import Any, List
from django.db.models import QuerySet
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import View, TemplateView, FormView
from django_htmx.http import trigger_client_event
from .forms import (
    ContactForm
)
from .task import send_feedback_email_task

from core.models import (
    Testimonial,
    Project
)

from blog.models import (
    Post
)

class HomePage(TemplateView):
    template_name = "core/pages/home.html"
    PROJECT_LIMIT :int = 2
    POST_LIMIT :int = 3
    TESTIMONIALS_LIMIT :int = 3


    def get_testimonials(self) -> QuerySet[Testimonial]:
        return Testimonial.published.all()[:self.TESTIMONIALS_LIMIT]

    def get_projects(self) -> list:
        return Project.published.all()[:self.PROJECT_LIMIT]
    
    def get_posts(self) -> QuerySet[Post]:
        """last published posts"""
        return Post.published.all()[:self.POST_LIMIT]
    

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context.update({
            "projects": self.get_projects(),
            "testimonials": self.get_testimonials(),
            "posts": self.get_posts()
        })
        return context
    
class AboutPage(TemplateView):
    template_name = "core/pages/about.html"
    PROJECT_LIMIT :int = 2
    POST_LIMIT :int = 3

class ContactFormPartialView(FormView):
    form_class = ContactForm
    template_name = "core/partials/home/contact_form.html"

    def form_valid(self, form) -> HttpResponse:
        response = self.render_to_response({})
        return trigger_client_event(
            response,
            "display_toast",
            {
                "status":200,
                "message":"Email Enviado. Revisa la Bandeja de Entrada tu Correo"
            }
        )
    
    def form_invalid(self, form) -> HttpResponse:
        response = super().form_invalid(form)
        return trigger_client_event(
            response,
            "display_toast",
            {
                "status":400,
                "message":"No fue posible enviar el su mensaje"
            }
        )   

    def post(self, request, *args, **kwargs):
        """
        Sends Async Email
        """
        form = self.get_form()
        if form.is_valid():
            form.send_email()
            return self.form_valid(form)
        else:
            if "username" in form.errors:
                return self.form_valid(form)
            else:
                return self.form_invalid(form)

project/core/templates/core/partials/base/navbar.html
<header
  x-data="{mobileOpen: false}"
  class="flex z-50 sticky top-0 flex-wrap md:justify-start md:flex-nowrap 
  w-full bg-gradient-to-t  from-[hsl(200,100%,8%)] to-[hsl(200,100%,18%)]
  text-white text-sm py-3 md:py-0 shadow-md">
    <nav class="max-w-[85rem] w-full mx-auto px-4 md:px-6 lg:px-8" aria-label="Global">
      <div class="relative md:flex md:items-center md:justify-between">
        <div class="flex items-center justify-between">
          <a class="flex-none text-xl font-oxanium font-semibold" href="{% url 'core:home' %}" aria-label="Brand">
            Keiner Mendoza
        </a>
        {% comment %} mobileIcon {% endcomment %}
          <div class="md:hidden">
            <button
              @click="mobileOpen = !mobileOpen" 
              type="button" class="flex justify-center items-center w-9 h-9 text-sm font-semibold rounded-lg border border-gray-200 text-gray-800 hover:bg-gray-100 disabled:opacity-50 disabled:pointer-events-none dark:text-white dark:border-gray-700 dark:hover:bg-gray-700 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600" data-hs-collapse="#navbar-collapse-with-animation" aria-controls="navbar-collapse-with-animation" aria-label="Toggle navigation">
              
              <svg
                x-show="!mobileOpen" 
                class="flex-shrink-0 w-4 h-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <line x1="3" x2="21" y1="6" y2="6" />
                <line x1="3" x2="21" y1="12" y2="12" />
                <line x1="3" x2="21" y1="18" y2="18" />
              </svg>
              <svg 
                x-show="mobileOpen"
                x-cloak
                class="flex-shrink-0 w-4 h-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M18 6 6 18" />
                <path d="m6 6 12 12" />
              </svg>
            </button>
          </div>
        </div>

        <nav
          class="fixed left-0 top-[3.75rem] min-h-screen w-screen bg-[rgba(0,0,0,0.8)]" 
          x-show="mobileOpen"
          x-cloak
          >
          <a href="">ok</a>
        </nav>



  
        <div id="navbar-collapse-with-animation" 
          class="hs-collapse d-none transition-all duration-300 basis-full grow md:block">
            <div class="flex flex-col gap-x-0 mt-5 divide-y divide-dashed divide-gray-200
              md:flex-row md:items-center md:justify-end md:gap-x-7 md:mt-0 md:ps-7 md:divide-y-0
              md:divide-solid dark:divide-gray-700">
  
            {% url 'core:home' as home_url %}
              <a 
                class="{% if home_url == request.path_info %}text-secundary{% else %}text-white{% endif %}
                font-medium cursor-pointer hover:underline underline-offset-4 py-3 md:py-6" 
                
                {% if home_url == request.path_info %}
                  aria-current="page"
                {% endif %}
                
                href="{{ home_url }}" 
                >Home</a>

              {% url 'core:about' as about_url %}
                <a 
                  class="{% if about_url == request.path_info %}text-secundary{% else %}text-white{% endif %}
                  font-medium cursor-pointer hover:underline underline-offset-4 py-3 md:py-6" 
                  
                  {% if about_url == request.path_info %}
                    aria-current="page"
                  {% endif %}
                  
                  href="{{ about_url }}" 
                  >Sobre Mi</a>
              
            
  
              {% url 'blog:list' as blog_url %}
              <a 
              class="{% if blog_url == request.path_info %}text-secundary{% else %}text-white{% endif %}
              font-medium cursor-pointer hover:underline underline-offset-4 py-3 md:py-6" 
              
              {% if blog_url == request.path_info %}
                aria-current="page"
              {% endif %}
              
              href="{{ blog_url }}" 
              >Publicaciones</a>
 
     
              {% if  user.is_authenticated %}

              <div x-data="{ open: false }" class="relative md:py-4">
                <button 
                    @click="open = ! open"
                    type="button"
                    class="flex items-center w-full text-gray-500 hover:text-gray-400 font-medium dark:text-gray-400 dark:hover:text-gray-500"
                  >
                    {{ user.username | capfirst}}
                  <svg class="ms-2 w-4 h-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <path d="m6 9 6 6 6-6" />
                  </svg>
                </button>
    
                <div 
                  x-cloak x-show="open" :class="open ? 'text-red-500' : 'text-blue-500'" @click.away="open = false" 
                  class="z-10 w-36 absolute top-16 right-0 bg-white border border-gray-200 rounded-lg shadow"
                  x-transition:enter="duration-200 ease-out"
                  x-transition:enter-start="opacity-0 -translate-y-5 scale-90"
                  x-transition:enter-end="opacity-100 translate-y-0 scale-100"

                >
    
                  {% comment %} <a class="flex items-center gap-x-3 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-300 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600" 
                    href="{% url 'parafrasis:profile' %}">
                    My Profile
                  </a> {% endcomment %}

                  <span
                    hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                    hx-swap="none"
                    hx-push-url="true"
                    hx-on::after-request="event.detail.successful && location.assign(event.detail.xhr.responseURL)"
                    hx-post="{% url 'account_logout' %}"
                    class="flex items-center gap-x-3.5 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-300 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600" 
                    >
                    Logout
                </span>
                </div>
              </div> 


              {% else %}

              <div class="pt-3 md:pt-0">
                <a class="py-2.5 px-4 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg 
                border border-transparent bg-primary text-white
                transition-all outline-offset-4 hover:outline hover:outline-2 hover:scale-105 hover:outline-white  
                disabled:opacity-50 disabled:pointer-events-none" 
                  href="{% url 'account_login' %}">
                  
                  <svg class="flex-shrink-0 w-4 h-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
                    <circle cx="12" cy="7" r="4" />
                  </svg>
                  Log in
                </a>
              </div>

              {% endif %} 
            
            </div>
          </div> 
        </div>
      </div>
    </nav>
  </header>

project/core/templates/core/partials/base/toast.html
{% load static %}
<template id="toast-template">
<div id="toast"
        class="toast appears-500 text-darkblue-card-gradient bg-cyan-400 
        w-[90%] z-50 font-semibold 
        p-2 rounded-lg border-2 border-solid border-darkblue-card-gradient
        flex justify-between items-center gap-2 
        fixed top-20 right-0 left-0 mx-auto      
        sm:w-fit sm:mr-0 sm:right-6
        ">
    <img id="toast-svg-icon" 
        class="w-5 h-5"
    src="{% static 'icons/check-badge.svg' %}" alt="toast status icon">
    <p id="toast-text-message"></p>
</div>
</template>

project/core/templates/core/partials/base/urls_css.html
{% load process_string %}
<style>
    @font-face{
        font-family: 'oxanium';
        src: url("{{'fonts/Oxanium-VariableFont_wght_new.woff'|clean_amperson}}") format('woff');
    }
    @font-face{
        font-family: 'poppins';
        src: url("{{'fonts/Poppins-Regular_new.woff'|clean_amperson }}") format('woff');
    }
    
    html {
        font-family: "poppins", system-ui, sans-serif;
    }
    
    .font-oxanium {
        font-family: 'oxanium',
    }
    
    .font-poppins {
        font-family: 'poppins',
    }
    
    .markdown-simple-container ul li::before{
        content: url("{{'icons/check-badge-solid_new.svg'|clean_amperson}}");
    }
    
    .form-container-hacker {
        background-image: url("{{'images/hacker_new.jpg'|clean_amperson}}");
        background-size: cover;
        background-position: center;
    }
</style>