project/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('email-contact/', views.email_contact, name='api_email_contact'),
]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    # path('account/', include('account.urls')),
    path('account/', include('allauth.urls')),

    path('', include('core.urls', namespace='core')),
    path('blog/', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

project/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path("", views.HomePage.as_view(), name="home"),
    path("about", views.AboutPage.as_view(), name="about"),
    path("contact-me", views.ContactFormPartialView.as_view(), name="contact_me"),

]

project/core/models.py
import markdown
from django.db import models
from blog.models import Topic
from django.core.exceptions import ValidationError
from django.utils.safestring import mark_safe
from .validators import for_published_status_require_image_not_none

class TestimonialManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status="P")

class Testimonial(models.Model):
    class Status(models.TextChoices):
        EDITING = ("E", "Editing")
        PUBLISHED = ("P", "Published")

    name = models.CharField(max_length=40)
    profession = models.CharField(max_length=80)
    message = models.CharField(max_length=250)
    image = models.FileField(upload_to="testimonials", blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=Status.choices, default=Status.EDITING)

    objects = models.Manager()  
    published = TestimonialManager()

    def clean(self):
        for_published_status_require_image_not_none(self.status, self.image)

    def save(self, *args, **kwargs):
        self.full_clean()
        return super().save(*args, **kwargs)
    
    def publish(self) -> None:
        self.status = Project.Status.PUBLISHED
        self.save()
    
    def unpublish(self) -> None:
        self.status = Project.Status.EDITING
        self.save()

    def __str__(self) -> str:
        return self.name

    class Meta:
        indexes = [
            models.Index(fields=["-created"])
        ]
        ordering = ["-created"]

class ProjectManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status="P")
    
class Project(models.Model):
    class Status(models.TextChoices):
        EDITING = ("E", "Editing")
        PUBLISHED = ("P", "Published")

    customer = models.CharField(max_length=40)
    customer_commercial_field = models.CharField(max_length=80)
    description = models.TextField()
    image = models.FileField(upload_to="projects", blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    tecnologies = models.ManyToManyField(Topic, related_name="projects")
    status = models.CharField(max_length=1, choices=Status.choices, default=Status.EDITING)
    
    objects = models.Manager()  
    published = ProjectManager()
        
    def clean(self):
        for_published_status_require_image_not_none(self.status, self.image)

    def save(self, *args, **kwargs):
        self.full_clean()
        return super().save(*args, **kwargs)
    
    @property
    def description_html(self) -> str:
        return mark_safe(markdown.markdown(self.description))
    
    def publish(self) -> None:
        self.status = Project.Status.PUBLISHED
        self.save()
    
    def unpublish(self) -> None:
        self.status = Project.Status.EDITING
        self.save()

    def __str__(self) -> str:
        return self.name

    class Meta:
        indexes = [
            models.Index(fields=["-created"])
        ]
        ordering = ["-created"]

project/core/forms.py
from typing import Any
from django import forms
from django.core.exceptions import ValidationError
from .task import send_feedback_email_task

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    best_email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)
    
    # trap fields
    username = forms.CharField(required=False)
    email = forms.CharField(required=False)
    
    def clean(self) -> dict[str, Any]:
        """
        checking fields for catch some bots
        """
        cleaned_data = super().clean()
        trap1 = cleaned_data.get("email")
        trap2 = cleaned_data.get("username")

        if trap1 or trap2:
            self.add_error("username", "stop the bot")
        return cleaned_data
    
    def send_email(self) -> None:
        """
        using celery task for send emails
        """
        email = self.cleaned_data.get("best_email")
        name = self.cleaned_data.get("name")
        message = self.cleaned_data.get("message")
        send_feedback_email_task.delay(email, message)

project/core/views.py
from typing import Any, List
from django.db.models import QuerySet
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import View, TemplateView, FormView
from django_htmx.http import trigger_client_event
from .forms import (
    ContactForm
)
from .task import send_feedback_email_task

from core.models import (
    Testimonial,
    Project
)

from blog.models import (
    Post
)

class HomePage(TemplateView):
    template_name = "core/pages/home.html"
    PROJECT_LIMIT :int = 2
    POST_LIMIT :int = 3
    TESTIMONIALS_LIMIT :int = 3


    def get_testimonials(self) -> QuerySet[Testimonial]:
        return Testimonial.published.all()[:self.TESTIMONIALS_LIMIT]

    def get_projects(self) -> list:
        return Project.published.all()[:self.PROJECT_LIMIT]
    
    def get_posts(self) -> QuerySet[Post]:
        """last published posts"""
        return Post.published.all()[:self.POST_LIMIT]
    

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context.update({
            "projects": self.get_projects(),
            "testimonials": self.get_testimonials(),
            "posts": self.get_posts()
        })
        return context
    
class AboutPage(TemplateView):
    template_name = "core/pages/about.html"
    PROJECT_LIMIT :int = 2
    POST_LIMIT :int = 3

class ContactFormPartialView(FormView):
    form_class = ContactForm
    template_name = "core/partials/home/contact_form.html"

    def form_valid(self, form) -> HttpResponse:
        response = self.render_to_response({})
        return trigger_client_event(
            response,
            "display_toast",
            {
                "status":200,
                "message":"Email Enviado. Revisa la Bandeja de Entrada tu Correo"
            }
        )
    
    def form_invalid(self, form) -> HttpResponse:
        response = super().form_invalid(form)
        return trigger_client_event(
            response,
            "display_toast",
            {
                "status":400,
                "message":"No fue posible enviar el su mensaje"
            }
        )   

    def post(self, request, *args, **kwargs):
        """
        Sends Async Email
        """
        form = self.get_form()
        if form.is_valid():
            form.send_email()
            return self.form_valid(form)
        else:
            if "username" in form.errors:
                return self.form_valid(form)
            else:
                return self.form_invalid(form)

project/core/templates/core/partials/home/contact.html
{% load static %}
<section id="contact" class="overflow-hidden relative px-4 md:px-6 lg:px-8 ">
    <img class="absolute bottom-0 left-0 w-screen min-h-20 object-cover z-0" src="{% static 'icons/many_buildings.svg' %}" alt="">
    <img class="absolute bottom-2 -right-30 opacity-40 w-screen min-h-16 object-cover z-0" src="{% static 'icons/many_buildings.svg' %}" alt="">

    <div class="relative max-w-7xl mx-auto flex flex-col md:flex-row gap-10 items-center md:items-start justify-between py-10">
        
        
        <article class="max-w-lg text-center md:text-left">
            <div class="pb-5 md:pb-10">
                <h2 class="text-4xl ">Contactame</h2>
            </div>
            <p class="text-xl pb-3">Inmediatamente recibiras una respuesta 
                automática y proximamente responderé
                personalmente al correo que hayas
                proporcionado</p>
            <p class="text-sm">
                La informacion proporcionada en el siguiente formulario no será almacenada.
            </p>
        </article>
        {% include "core/partials/home/contact_form.html" %}
    </div>
</section>

project/core/templates/core/partials/home/contact_form.html
<div id="home-contact-contact-form-container"  class=" relative overflow-hidden p-4 rounded-md max-w-lg form-container-hacker" >
    <form id="contact-form"
        method="post" 
        action="{% url 'core:contact_me' %}"
        hx-post="{% url 'core:contact_me' %}"
        hx-swap="outerHTML transition:true"
        hx-target="#home-contact-contact-form-container"
        >
        <div class="p-3 mb-5 grid gap-3 bg-opacity-60 rounded-md bg-white">
            {% csrf_token %}
            <input 
            class="absolute translate-x-[999999px]"
            tabindex="-1" 
            type="text" name="username" id="username">
            <input 
            class="absolute translate-x-[999999px]"
            tabindex="-1" 
            type="text" name="email" id="email">


            <label class="text-lg" for="name">Name</label>
            {% for error in form.name.errors %}
                <p class="max-w-80 text-red-900 text-sm mb-[0.15em]">{{ error }}</p>
            {% endfor %}
            <input 
                class="transition-colors hover:cursor-pointer border-2 hover:border-primary px-2 py-1 rounded-md" 
                type="text" required name="name" id="name" 
                value="{% if form.name %}{{ form.name.value|default_if_none:"" }}{% endif %}">
            <label class="text-lg" for="best_email">Email</label>

            {% for error in form.best_email.errors %}
                <p class="max-w-80 text-red-900 text-sm mb-[0.15em]">{{ error }}</p>
            {% endfor %}
            <input
                class="transition-colors hover:cursor-pointer border-2 hover:border-primary px-2 py-1 rounded-md" 
                type="email" name="best_email" id="best_email"
                value="{% if form.best_email %}{{ form.best_email.value|default_if_none:"" }}{% endif %}">

            <label class="text-lg" for="message">Message</label>
            
            {% for error in form.message.errors %}
                <p class="max-w-80 text-red-900 text-sm mb-[0.15em]">{{ error }}</p>
            {% endfor %}
            <textarea
                class="transition-colors hover:cursor-pointer border-2 hover:border-primary px-2 py-1 rounded-md" 
                name="message" id="message" cols="30" required rows="4">{% if form.message %}{{ form.message.value|default_if_none:"" }}{% endif %}</textarea>
            
            

        </div>
        <div class="text-right">
            <button 
            form="contact-form"
            class="primary-button-color-font px-8 pt-3 pb-2 rounded-md text-xl"
            type="submit">enviar</button>
        </div>
    </form>
</div>

project/core/templates/core/partials/home/hero.html
{% load static  %}

<section class=" overflow-hidden px-4 md:px-6 lg:px-8 bg-gradient-to-br text-white from-[#002861] to-[hsl(215,100%,45%)] relative h-[clamp(600px,80vw,min(90vh,800px))] " 
    id="hero">
    <div class="max-w-7xl h-full mx-auto">

        <!-- wave and background wave -->
        <div id="hero-background-same-as-wave"
            class="bg-gradient-to-r from-[rgba(173,212,235,0.8)] to-[#ADD4EB] absolute left-0 w-1/2 h-full 
            z-0 hidden lg:block"></div>
        <svg
            class="absolute hidden lg:block inset-0 mx-auto translate-x-[45%] top-0 h-full"
            viewBox="0 0 320 1440">
        <path
            fill="#ADD4EB"
            fill-opacity="1"
            d="m 224,0 -5.3,21.8 C 213,43.6 203,87 197.3,131 192,174.5 192,218 192,262 c 0,43.5 0,87 5.3,131 5.7,43.4 15.7,87 -5.3,131 -21,43.3 -75,87 -101.3,131 -26.7,43.2 -26.7,87 0,130 26.3,44.1 80.3,88 69.3,131 -11,44 -85,88 -112,131 -27,43.9 -5,88 32,131 37,43.8 91,87 101.3,131 10.7,43.7 -21.3,87 -37.3,109 l -16,22 H 0 v -21.8 C 0,1396.4 0,1353 0,1309 0,1265.5 0,1222 0,1178 0,1134.5 0,1091 0,1047 0,1003.6 0,960 0,916 0,872.7 0,829 0,785 0,741.8 0,698 0,655 0,610.9 0,567 0,524 0,480 0,436 0,393 0,349.1 0,305 0,262 0,218.2 0,175 0,131 0,87.3 0,44 0,22 V 0 Z"
            id="path1" />
        </svg>

        <!-- tooltips -->
        <div id="tooltips-container"
                
            class="absolute left-0 right-0 mx-auto bottom-0 
            md:left-auto md:m-0 md:right-8 w-2/5  min-w-72 h-2/3 md:h-2/3 lg:h-5/6">
            <div data-name="idiomas" 
                data-tooltip="Me encanta el Desarrollo Web, imprimo esa pasion en todas las etapas del desarrollo, hasta llevar los requerimientos del producto a producción." 
                data-preference="to-left"
                x-data="{animate: false}"
                x-init="setTimeout(() => {animate=true}, 1000)"
                x-cloak
                x-show="animate"
                x-bind:class="animate && 'appears-300'"
                class="tooltip-hero-basic-style
                top-1/2 left-1/2 
                lg:translate-y-20">
                <svg 
                    class="rounded-full outline outline-2 outline-black outline-offset-4
                    w-4 h-4 sm:w-6 sm:h-6" 
                    xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                    <path stroke-linecap="round" stroke="black" stroke-linejoin="round" d="M7.5 8.25h9m-9 3H12m-9.75 1.51c0 1.6 1.123 2.994 2.707 3.227 1.129.166 2.27.293 3.423.379.35.026.67.21.865.501L12 21l2.755-4.133a1.14 1.14 0 0 1 .865-.501 48.172 48.172 0 0 0 3.423-.379c1.584-.233 2.707-1.626 2.707-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0 0 12 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018Z" />
                </svg>
                <p class="text-black flex gap-1"><span class="hidden sm:block md:hidden lg:block">Multiples</span>Idiomas</p>
            </div>
            <div  data-name="pasion"
                data-tooltip="Me encanta el Desarrollo Web, imprimo esa pasion en todas las etapas del desarrollo, desde entender los requerimientos del sitio, realizar el diseño y llevarlo todo a producción." 
                data-preference="to-right-md-left"
                x-data="{animate: false}"
                x-init="setTimeout(() => {animate=true}, 1000)"
                x-cloak
                x-show="animate"
                x-bind:class="animate && 'appears-300'"
                class="tooltip-hero-basic-style
                top-1/3 left-0
                sm:-left-12 
                lg:left-0
                lg:translate-y-16
                2xl:left-[10%]">
                <svg 
                    class="rounded-full outline outline-2 outline-black outline-offset-4
                    w-4 h-4 sm:w-6 sm:h-6" 
                    xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                    <path stroke-linecap="round" stroke="black" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12Z" />
                </svg>
                <span class="text-black">Pasion</span>
            </div>
            <div data-name="fullstack" 
                data-tooltip="Me encanta el Desarrollo Web, imprimo esa pasion en todas las etapas del desarrollo, hasta llevar los requerimientos del producto a producción." 
                data-preference="to-left"
                x-data="{animate: false}"
                x-init="setTimeout(() => {animate=true}, 1000)"
                x-cloak
                x-show="animate"
                x-bind:class="animate && 'appears-300'"
                class="tooltip-hero-basic-style
                top-0 right-0 
                sm:-top-8 sm:-right-32 
                md:-right-4
                lg:top-0
                2xl:right-[5%]">
                <svg
                    class="rounded-full outline outline-2 outline-black outline-offset-4
                    w-4 h-4 sm:w-6 sm:h-6" 
                    xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                    <path stroke="black" stroke-linecap="round" stroke-linejoin="round" d="M3 13.125C3 12.504 3.504 12 4.125 12h2.25c.621 0 1.125.504 1.125 1.125v6.75C7.5 20.496 6.996 21 6.375 21h-2.25A1.125 1.125 0 0 1 3 19.875v-6.75ZM9.75 8.625c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125v11.25c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 0 1-1.125-1.125V8.625ZM16.5 4.125c0-.621.504-1.125 1.125-1.125h2.25C20.496 3 21 3.504 21 4.125v15.75c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 0 1-1.125-1.125V4.125Z" />
                </svg>
                <span class="text-black flex gap-1"><span class="hidden sm:block md:hidden lg:block">Desarrollo</span>Fullstack</span>
            </div>
        </div>
        
        <!-- my photo -->
        <figure class="z-10 absolute left-0 right-0 mx-auto bottom-0 md:left-auto md:m-0 md:right-8 w-2/5  min-w-72 h-[75vh] ">
            <img src="{% static 'core/images/me_profile.png' %}" alt="keiner mendoza"
            class="w-full h-full object-contain object-bottom">
        </figure>

        <!-- text and call to action section -->
        <article 
            class="relative z-10 pt-10 md:pt-20 h-full flex flex-col md:block justify-start items-center text-center md:text-left lg:text-darkblue-card-gradient">
            <h2 class="text-2xl md:text-3xl xl:text-4xl mb-5">Keiner Mendoza</h2>
            <h1 class="text-3xl sm:text-4xl md:text-5xl xl:text-6xl mb-8 flex flex-wrap justify-center md:block">
                <span class="whitespace-pre">DESARROLLADOR </span>
                <span>WEB</span>
            </h1>

            <div class="relative z-20 grow flex flex-col items-center justify-end md:block">
                <div class="hidden md:block xl:text-xl max-w-sm lg:max-w-md xl:max-w-lg">
                    <p class="mb-4 lg:mb-4">
                        Creo páginas web personalizadas para empresas, personas o eventos. Tendrás un sitio donde publicar lo que quieras con libertad y estilo.
                    </p>
                    <p>
                        También estoy abierto a trabajar en equipo a tiempo parcial o completo.
                    </p>
                </div>

                <a href="#contact"
                x-data="{animate: false}"
                x-init="setTimeout(() => {animate=true}, 1000)"
                x-cloak
                x-show="animate"
                x-bind:class="animate && 'appears-300'"
                class="primary-button-color-font pb-2 pt-3 px-8 mb-10 md:mt-10 lg:mt-16 xl:mt-28 xl:px-10 xl:pb-3 xl:pt-4  
                flex justify-between items-center gap-5 w-fit shadow-md rounded-md">
                <span class="text-2xl sm:text-3xl xl:text-4xl">contactame</span>
                <img class="w-10 h-10 xl:relative xl:bottom-[2px]" src="{% static 'icons/mail.svg' %}" alt="">
                </a>
            </div>
        </article>
    </div>
</section>

project/core/templates/core/partials/home/posts.html
{% load static %}
<section class="bg-custom-gray px-4 md:px-6 lg:px-8" id="posts">
    <div class="max-w-7xl mx-auto flex flex-col items-center gap-5">
        <div class="text-center py-10">
            <h2 class="text-4xl">ULTIMAS PUBLICACIONES</h2>
        </div>

        <div 
            id="posts-container"
            x-data="{lastItemShow:false, checkSize(){this.lastItemShow = window.innerWidth <= 768 || window.innerWidth >= 1024 }}"
            class="grid md:grid-cols-2 lg:grid-cols-3 gap-5"
        >
            {% for post in posts %}
            <article
                {% if forloop.last %}
                id="lastItem"
                x-show="lastItemShow"
                x-cloak
                x-init="checkSize()"
                x-on:resize.window="checkSize()"
                {% endif %} 
                class="max-w-lg p-5 rounded-lg shadow-lg bg-white flex flex-col gap-5">
                <a href="{{post.get_absolute_url}}"
                    class="p-3 rounded-md border-2 border-custom-gray flex justify-between items-center gap-5
                    transition-all hover:cursor-pointer hover:bg-primary 
                    hover:outline outline-2  hover:outline-darkblue-card-gradient
                ">
                    <h3 class="text-xl">{{post.title}}</h3>
                    <img
                        class="w-6 h-6"
                    src="{% static 'icons/arrow-right.svg' %}" alt="Read the article">
                </a>
                <figure class="bg-custom-gray w-full min-h-60 rounded-md grid">
                    <img 
                        class="w-3/4 place-self-center"
                    src="{% static post.image %}" alt="representative image of {{post.title}}">
                </figure>
                <div>
                    <p>{{post.preview}}</p>
                </div>

            </article>
            {% endfor %}
        </div>

        <div class="text-center py-10 ">
            <a class="primary-button-color-font block text-xl px-6 pt-3 pb-2 rounded-lg shadow-lg" 
            href="#todos-los-proyectos">
            ver todas las publicaciones
            </a>
        </div>
    </div>
</section>

project/core/templates/core/partials/home/projects.html
{% load static markdown %}

<section id="projects" class="px-4 md:px-6 lg:px-8 bg-custom-gray" id="porjects">
    <div class="max-w-7xl mx-auto">

        <div class="text-center py-10">
            <h2 class="text-4xl">PRINCIPALES PROYECTOS</h2>
            <p class="text-xl">Sitios web reales para clientes reales</p>
        </div>

        <div id="project-cards-container"
            class="grid grid-cols-2 lg:grid-cols-3 gap-5"
        >
            {% for project in projects %}

            {% if forloop.counter|divisibleby:2 %}
                {% include 'project_tecnologies_card.html' with tecnologies=tecnologies light_tr=True %}
            {% endif %}

            <article class="col-span-2 min-h-[400px] gap-3 p-3 sm:gap-5 sm:p-5 flex md:flex-row flex-col
             bg-white rounded-xl shadow-xl
             {% if forloop.counter|divisibleby:2 %}lg:col-start-2{% else %}lg:col-start-1{% endif %}">
  
                <header class="flex flex-col gap-3 flex-1">
                    <h3 class="uppercase text-2xl">{{ project.customer}}</h3>
                    <a class="text-primary" href="">
                        <span>SVG</span>
                        <span>Visitar Sitio</span>
                    </a>
                    <figure class="grow rounded-lg overflow-hidden">
                        <img src="{% static project.image %}" alt="{{project.customer}}"
                            class="w-full h-full object-cover"
                        >
                    </figure>
                </header>
                <div class="flex flex-col items-start md:mt-9 md:px-3 gap-3 flex-1">
                    <p class="hidden sm:block text-xl text-gray-600">{{project.customer_commercial_field}}</p>
                    <div class="markdown-simple-container">
                        {{ project.description|markdown }}
                    </div>
                </div>
            </article>
           
            {% if forloop.counter0|divisibleby:2 %}
                {% include 'project_tecnologies_card.html' with tecnologies=tecnologies %}
            {% endif %}
            
            {% endfor %}
        </div>    

        <div class="flex justify-center items-center py-10 ">
            <a class="primary-button-color-font block text-2xl px-6 pt-3 pb-2
            rounded-lg shadow-lg bg-gradient-to-bl from-primary to-darkblue-card" href="#todos-los-proyectos">Ver Mas</a>
        </div>
    </div>
</section>

project/core/templates/core/partials/home/testimonials.html
<section class="px-4 md:px-6 lg:px-8 py-10 text-white bg-darkblue-back" id="testimonials">
    <div class="max-w-7xl mx-auto relative">
        <div class="text-center sm:pb-10">
            <h2 class="text-4xl">TESTIMONIALS</h2>
        </div>

        <!-- transition clock -->
        <div class="autoplay-progress
        z-0 inset-0 mx-auto
        relative my-5 
        sm:my-0 sm:absolute 
        sm:top-0 sm:translate-x-[180px] sm:-translate-y-1 
        xl:translate-y-0 xl:translate-x-0 xl:top-[50%] ">
            <svg viewBox="0 0 48 48">
              <circle cx="24" cy="24" r="20"></circle>
            </svg>
            <span></span>
        </div>

        <!-- 'testimonial_card.html' is in  '/project/template_components' -->
        <div class="swiper" id="testimonial-wrapper">
            <div class="swiper-wrapper">
                {% for testimonial in testimonials %}
                    {% include 'testimonial_card.html' with testimonial=testimonial %}
                {% endfor %}

                
                {% with testimonials|length as testimonials_length %}
                {% if testimonials_length < 3 %}
                {% for testimonial in testimonials %}
                    {% include 'testimonial_card.html' with testimonial=testimonial %}
                {% endfor %}
                {% endif %}
                {% endwith %}
            </div>
        </div>
    </div>
</section>